In [3]:
import pandas as pd
import numpy as np

In [22]:
df = pd.DataFrame({'weight':[65,45,67,71,54,np.nan],
                  'name':['john','sarah','alex','rohit','mia','sd'],
                  'gender':['male','female','male','male','female','female'],
                  'age':[23,25,27,21,26,np.nan],
                  'isgraduated':[False,True,True,False,True,False]})

In [14]:
df1=df[['weight','age']]

In [15]:
df1.describe()

weight        age
count   5.000000   5.000000
mean   60.400000  24.400000
std    10.667708   2.408319
min    45.000000  21.000000
25%    54.000000  23.000000
50%    65.000000  25.000000
75%    67.000000  26.000000
max    71.000000  27.000000

In [64]:
df2 = df[['name','gender']]

In [19]:
df.describe(exclude=int)

weight  name gender        age isgraduated
count    5.000000     6      6   5.000000           6
unique        NaN     6      3        NaN           2
top           NaN  john   male        NaN       False
freq          NaN     1      3        NaN           3
mean    60.400000   NaN    NaN  24.400000         NaN
std     10.667708   NaN    NaN   2.408319         NaN
min     45.000000   NaN    NaN  21.000000         NaN
25%     54.000000   NaN    NaN  23.000000         NaN
50%     65.000000   NaN    NaN  25.000000         NaN
75%     67.000000   NaN    NaN  26.000000         NaN
max     71.000000   NaN    NaN  27.000000         NaN

In [23]:
df_get_dummies = pd.get_dummies(df)

In [24]:
df_get_dummies

weight   age  isgraduated  name_alex  name_john  name_mia  name_rohit  \
0    65.0  23.0        False          0          1         0           0   
1    45.0  25.0         True          0          0         0           0   
2    67.0  27.0         True          1          0         0           0   
3    71.0  21.0        False          0          0         0           1   
4    54.0  26.0         True          0          0         1           0   
5     NaN   NaN        False          0          0         0           0   

   name_sarah  name_sd  gender_female  gender_male  
0           0        0              0            1  
1           1        0              1            0  
2           0        0              0            1  
3           0        0              0            1  
4           0        0              1            0  
5           0        1              1            0

In [154]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X = imputer.fit_transform(df1)

imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
y = imputer.fit_transform(df)

In [37]:
X,y

(array([[65. , 23. ],
        [45. , 25. ],
        [67. , 27. ],
        [71. , 21. ],
        [54. , 26. ],
        [60.4, 24.4]]),
 array([[65.0, 'john', 'male', 23.0, False],
        [45.0, 'sarah', 'female', 25.0, True],
        [67.0, 'alex', 'male', 27.0, True],
        [71.0, 'rohit', 'male', 21.0, False],
        [54.0, 'mia', 'female', 26.0, True],
        [45.0, 'sd', 'female', 21.0, False]], dtype=object))

In [42]:
df_horse = pd.read_csv("D:\Study\DS\horse-colic.csv",
                      header=None,delimiter=" ",na_values='?')

In [43]:
df_horse

0   1        2     3      4     5    6    7    8    9   ...    18    19  \
0    2.0   1   530101  38.5   66.0  28.0  3.0  3.0  NaN  2.0  ...  45.0   8.4   
1    1.0   1   534817  39.2   88.0  20.0  NaN  NaN  4.0  1.0  ...  50.0  85.0   
2    2.0   1   530334  38.3   40.0  24.0  1.0  1.0  3.0  1.0  ...  33.0   6.7   
3    1.0   9  5290409  39.1  164.0  84.0  4.0  1.0  6.0  2.0  ...  48.0   7.2   
4    2.0   1   530255  37.3  104.0  35.0  NaN  NaN  6.0  2.0  ...  74.0   7.4   
..   ...  ..      ...   ...    ...   ...  ...  ...  ...  ...  ...   ...   ...   
295  1.0   1   533886   NaN  120.0  70.0  4.0  NaN  4.0  2.0  ...  55.0  65.0   
296  2.0   1   527702  37.2   72.0  24.0  3.0  2.0  4.0  2.0  ...  44.0   NaN   
297  1.0   1   529386  37.5   72.0  30.0  4.0  3.0  4.0  1.0  ...  60.0   6.8   
298  1.0   1   530612  36.5  100.0  24.0  3.0  3.0  3.0  1.0  ...  50.0   6.0   
299  1.0   1   534618  37.2   40.0  20.0  NaN  NaN  NaN  NaN  ...  36.0  62.0   

      20   21   22  23     24  25  26  27  
0    NaN  NaN  2.0   2  11300   0   0   2  
1    2.0  2.0  3.0   2   2208   0   0   2  
2    NaN  NaN  1.0   2      0   0   0   1  
3    3.0  5.3  2.0   1   2208   0   0   1  
4    NaN  NaN  2.0   2   4300   0   0   2  
..   ...  ...  ...  ..    ...  ..  ..  ..  
295  NaN  NaN  3.0   2   3205   0   0   2  
296  3.0  3.3  3.0   1   2208   0   0   1  
297  NaN  NaN  2.0   1   3205   0   0   2  
298  3.0  3.4  1.0   1   2208   0   0   1  
299  1.0  1.0  3.0   2   6112   0   0   2  

[300 rows x 28 columns]

In [52]:
imputer1 = SimpleImputer(missing_values=np.nan, strategy='mean')
X_horse = imputer1.fit_transform(df_horse)

imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
y_horse = imputer1.fit_transform(df_horse)

In [53]:
X_horse,y_horse

(array([[2.00000e+00, 1.00000e+00, 5.30101e+05, ..., 0.00000e+00,
         0.00000e+00, 2.00000e+00],
        [1.00000e+00, 1.00000e+00, 5.34817e+05, ..., 0.00000e+00,
         0.00000e+00, 2.00000e+00],
        [2.00000e+00, 1.00000e+00, 5.30334e+05, ..., 0.00000e+00,
         0.00000e+00, 1.00000e+00],
        ...,
        [1.00000e+00, 1.00000e+00, 5.29386e+05, ..., 0.00000e+00,
         0.00000e+00, 2.00000e+00],
        [1.00000e+00, 1.00000e+00, 5.30612e+05, ..., 0.00000e+00,
         0.00000e+00, 1.00000e+00],
        [1.00000e+00, 1.00000e+00, 5.34618e+05, ..., 0.00000e+00,
         0.00000e+00, 2.00000e+00]]),
 array([[2.00000e+00, 1.00000e+00, 5.30101e+05, ..., 0.00000e+00,
         0.00000e+00, 2.00000e+00],
        [1.00000e+00, 1.00000e+00, 5.34817e+05, ..., 0.00000e+00,
         0.00000e+00, 2.00000e+00],
        [2.00000e+00, 1.00000e+00, 5.30334e+05, ..., 0.00000e+00,
         0.00000e+00, 1.00000e+00],
        ...,
        [1.00000e+00, 1.00000e+00, 5.29386e+05, ..., 0

In [57]:
from sklearn.impute import KNNImputer

knn_imputer = KNNImputer(missing_values=np.nan)
K = knn_imputer.fit_transform(df_horse)

In [58]:
K

array([[2.00000e+00, 1.00000e+00, 5.30101e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.34817e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [2.00000e+00, 1.00000e+00, 5.30334e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       ...,
       [1.00000e+00, 1.00000e+00, 5.29386e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.30612e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.34618e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00]])

In [61]:
pip install category_encoders

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



In [62]:
import category_encoders as ce
cats = df_horse[[0,1]]
one_hot_enc = ce.OneHotEncoder(cols=cats)

In [63]:
one_hot_enc

OneHotEncoder(cols=       0  1
0    2.0  1
1    1.0  1
2    2.0  1
3    1.0  9
4    2.0  1
..   ... ..
295  1.0  1
296  2.0  1
297  1.0  1
298  1.0  1
299  1.0  1

[300 rows x 2 columns])

In [69]:
ct_df2 = ce.OneHotEncoder(cols=df2)
ct_df2.fit_transform(df2)

name_1  name_2  name_3  name_4  name_5  name_6  gender_1  gender_2
0       1       0       0       0       0       0         1         0
1       0       1       0       0       0       0         0         1
2       0       0       1       0       0       0         1         0
3       0       0       0       1       0       0         1         0
4       0       0       0       0       1       0         0         1
5       0       0       0       0       0       1         0         1

In [67]:
ct_df2

OneHotEncoder(cols=    name  gender
0   john    male
1  sarah  female
2   alex    male
3  rohit    male
4    mia  female
5     sd  female)

In [71]:
from sklearn.preprocessing import LabelEncoder
label_encoder_x = LabelEncoder()
df_horse_01= label_encoder_x.fit_transform(df_horse[0])
df_horse_01

array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       2, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0], d

In [73]:
df['gender'] = label_encoder_x.fit_transform(df['gender'])
df['gender']

0    1
1    0
2    1
3    1
4    0
5    0
Name: gender, dtype: int32

In [76]:
onehot_encoder = ce.OneHotEncoder()

x= onehot_encoder.fit_transform(df).to_xarray()

In [77]:
x

<xarray.Dataset>
Dimensions:      (index: 6)
Coordinates:
  * index        (index) int64 0 1 2 3 4 5
Data variables:
    weight       (index) float64 65.0 45.0 67.0 71.0 54.0 nan
    name_1       (index) int64 1 0 0 0 0 0
    name_2       (index) int64 0 1 0 0 0 0
    name_3       (index) int64 0 0 1 0 0 0
    name_4       (index) int64 0 0 0 1 0 0
    name_5       (index) int64 0 0 0 0 1 0
    name_6       (index) int64 0 0 0 0 0 1
    gender       (index) int32 1 0 1 1 0 0
    age          (index) float64 23.0 25.0 27.0 21.0 26.0 nan
    isgraduated  (index) bool False True True False True False

In [79]:
from sklearn.preprocessing import StandardScaler,Normalizer,MinMaxScaler,PowerTransformer

In [80]:
min_max_df = MinMaxScaler()
min_max_df_x = min_max_df.fit_transform(pd.DataFrame(df_horse[2]))
[min_max_df_x.max(),min_max_df_x.min()]

[1.0, 0.0]

In [84]:
st_x=StandardScaler()
x_train = st_x.fit_transform(pd.DataFrame(df_horse_01))
x_train.mean(),x_train.std()

(1.7763568394002505e-17, 1.0)

In [88]:
nm_x = Normalizer()
x_train1 = nm_x.fit_transform(pd.DataFrame(df_horse_01))
print(x_train1.min(),x_train1.max())

0.0 1.0


In [90]:
pt_x = PowerTransformer()
x_train2 = pt_x.fit_transform(pd.DataFrame(df_horse_01))
print(x_train2.min(),x_train2.max())
print(x_train2.mean(),x_train2.std())

-0.8162456160428138 1.6519848728924396
1.0658141036401502e-16 1.0


In [95]:
import numpy as np
from sklearn.model_selection import train_test_split

X,y = np.arange(10).reshape((5,2)),range(5)
X_train,X_test,y_train,y_test = train_test_split(X,y,
                                                test_size=0.2,
                                                shuffle=False)

In [98]:
X_train,X_test,y_train,y_test

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]),
 array([[8, 9]]),
 [0, 1, 2, 3],
 [4])

In [100]:
from sklearn.model_selection import KFold

X = np.array([[1,2],[3,4],[1,2],[3,4]])
y = np.array([1,2,3,4])
kf = KFold(n_splits=3)

for train_index, test_index in kf.split(X):
    print("TRAIN:",train_index,"TEST:",test_index)
    X_train,X_test = X[train_index], X[test_index]
    print(X_train,X_test)
    y_train,y_test = y[train_index], y[test_index]
    print(y_train,y_test)


TRAIN: [2 3] TEST: [0 1]
[[1 2]
 [3 4]] [[1 2]
 [3 4]]
[3 4] [1 2]
TRAIN: [0 1 3] TEST: [2]
[[1 2]
 [3 4]
 [3 4]] [[1 2]]
[1 2 4] [3]
TRAIN: [0 1 2] TEST: [3]
[[1 2]
 [3 4]
 [1 2]] [[3 4]]
[1 2 3] [4]


In [101]:
kf = KFold(n_splits=3)
X_1,X_2,X_3 = kf.split(X_horse)


In [102]:
X_1,X_2,X_3

((array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
         113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
         126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
         139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
         152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
         165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
         178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
         191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203,
         204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216,
         217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229,
         230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
         243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
         256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268,
         269, 270, 271, 272, 273, 274,

In [104]:
from sklearn.model_selection import LeaveOneOut

X = np.array([[1,2],[3,4]])
y = np.array([1,2])
loo = LeaveOneOut()

for train_index, test_index in loo.split(X):
    print("TRAIN:",train_index,"TEST:",test_index)
    X_train,X_test = X[train_index], X[test_index]
    print(X_train,X_test)
    y_train,y_test = y[train_index], y[test_index]
    print(y_train,y_test)

TRAIN: [1] TEST: [0]
[[3 4]] [[1 2]]
[2] [1]
TRAIN: [0] TEST: [1]
[[1 2]] [[3 4]]
[1] [2]


In [105]:
from sklearn.model_selection import StratifiedKFold

X = np.array([[1,2],[3,4],[1,2],[3,4]])
y = np.array([0,0,1,1])
skf = StratifiedKFold(n_splits=2)

for train_index, test_index in skf.split(X,y):
    print("TRAIN:",train_index,"TEST:",test_index)
    X_train,X_test = X[train_index], X[test_index]
    y_train,y_test = y[train_index], y[test_index]
    

TRAIN: [1 3] TEST: [0 2]
TRAIN: [0 2] TEST: [1 3]


In [114]:
data

2 1 530101 38.50 66 28 3 3 ? 2 5 4 4 ? ? ? 3 5 45.00 8.40 ? ? 2 2 11300 00000 00000 2
0    1 1 534817 39.2 88 20 ? ? 4 1 3 4 2 ? ? ? 4 2 ...                                   
1    2 1 530334 38.30 40 24 1 1 3 1 3 3 1 ? ? ? 1 1...                                   
2    1 9 5290409 39.10 164 84 4 1 6 2 2 4 4 1 2 5.0...                                   
3    2 1 530255 37.30 104 35 ? ? 6 2 ? ? ? ? ? ? ? ...                                   
4    2 1 528355 ? ? ? 2 1 3 1 2 3 2 2 1 ? 3 3 ? ? ?...                                   
..                                                 ...                                   
294  1 1 533886 ? 120 70 4 ? 4 2 2 4 ? ? ? ? ? 5 55...                                   
295  2 1 527702 37.20 72 24 3 2 4 2 4 3 3 3 1 ? 4 4...                                   
296  1 1 529386 37.50 72 30 4 3 4 1 4 4 3 2 1 ? 3 5...                                   
297  1 1 530612 36.50 100 24 3 3 3 1 3 3 3 3 1 ? 4 ...                                   
298  1 1 534618 37.2 40 20 ? ? ? ? ? ? ? ? ? ? 4 1 ...                                   

[299 rows x 1 columns]

In [108]:
from sklearn.model_selection import RepeatedKFold

X = np.array([[1,2],[3,4],[1,2],[3,4]])
y = np.array([0,0,1,1])
rkf = RepeatedKFold(n_splits=2,n_repeats=2,random_state=42)

for train_index, test_index in rkf.split(X,y):
    print("TRAIN:",train_index,"TEST:",test_index)
    X_train,X_test = X[train_index], X[test_index]
    y_train,y_test = y[train_index], y[test_index]

TRAIN: [0 2] TEST: [1 3]
TRAIN: [1 3] TEST: [0 2]
TRAIN: [0 2] TEST: [1 3]
TRAIN: [1 3] TEST: [0 2]


In [109]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [166]:
# binary classification, missing data, impute with mean

import numpy
from pandas import read_csv
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
# from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression 
from sklearn.naive_bayes import GaussianNB 
from sklearn.neighbors import KNeighborsClassifier

# Load data

# df_horse = df_horse.values()

# split data into x and y 
X = df_horse[:,0:27]
Y = df_horse[:,27]

# set missing values to nan 
#X[X == '?'] = numpy.nan

# convert to numeric 
X = X.astype('float32')

# impute missing values as the mean 
imputed = SimpleImputer()
imputed_X = imputer.fit_transform(X)

# encode Y class values as integers
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(Y)
label_encoded_y= label_encoder.transform(Y)

# split data into x and y 
X = df_horse[:,0:27]
Y = df_horse[:,27]

# set missing values to nan 
#X[X == '?'] = numpy.nan

# convert to numeric 
X = X.astype('float32')

# impute missing values as the mean 
imputed = SimpleImputer()
imputed_X = imputer.fit_transform(X)

# encode Y class values as integers
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(Y)
label_encoded_y= label_encoder.transform(Y)

# split data into train and test sets
seed = 7
test_size = 0.33
X_train, X_test, y_train, y_test = train_test_split(imputed_X,
                                                    label_encoded_y,
                                                    test_size=test_size,
                                                    random_state=seed)

# fit model no training data
model_lg = LogisticRegression() 
model_lg.fit(X_train, y_train) 
print(model_lg)

# make predictions for test data
y_pred = model_lg.predict(X_test)
predictions=[round(value) for value in y_pred]

# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy*100.0))

LogisticRegression()
Accuracy: 65.66%


In [167]:
from sklearn.tree import DecisionTreeClassifier

params_1 = {'criterion':'gini','splitter':'best','max_depth':50}
params_2 = {'criterion':'entropy','splitter':'random','max_depth':70}
params_3 = {'criterion':'gini','splitter':'random','max_depth':60}
params_4 = {'criterion':'entropy','splitter':'best','max_depth':80}
params_5 = {'criterion':'gini','splitter':'best','max_depth':45}

model_1 = DecisionTreeClassifier(**params_1)
model_2 = DecisionTreeClassifier(**params_2)
model_3 = DecisionTreeClassifier(**params_3)
model_4 = DecisionTreeClassifier(**params_4)
model_5 = DecisionTreeClassifier(**params_5)

model_1.fit(X_train,y_train)
model_2.fit(X_train,y_train)
model_3.fit(X_train,y_train)
model_4.fit(X_train,y_train)
model_5.fit(X_train,y_train)


preds_1 = model_1.predict(X_test)
preds_2 = model_2.predict(X_test)
preds_3 = model_3.predict(X_test)
preds_4 = model_4.predict(X_test)
preds_5 = model_5.predict(X_test)

print(f"accuracy of model 1: {round(accuracy_score(y_test,preds_1),3)}")
print(f"accuracy of model 2: {round(accuracy_score(y_test,preds_2),3)}")
print(f"accuracy of model 3: {round(accuracy_score(y_test,preds_3),3)}")
print(f"accuracy of model 4: {round(accuracy_score(y_test,preds_4),3)}")
print(f"accuracy of model 5: {round(accuracy_score(y_test,preds_5),3)}")

accuracy of model 1: 0.768
accuracy of model 2: 0.758
accuracy of model 3: 0.758
accuracy of model 4: 0.768
accuracy of model 5: 0.737


In [168]:
df = pd.read_csv("D:\Study\DS\pima-indians-diabetes.csv",header=None)

In [169]:
df.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

In [170]:
from sklearn.model_selection import GridSearchCV
knn_clf = KNeighborsClassifier()

In [171]:
knn_clf

KNeighborsClassifier()

In [172]:
param_grid = {'n_neighbors': list(range(1,9)),'algorithm':('auto','ball_tree','kd_tree','brute')}

In [173]:
gs = GridSearchCV(knn_clf,param_grid,cv=10)
gs.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ('auto', 'ball_tree', 'kd_tree', 'brute'),
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8]})

In [174]:
gs.cv_results_['params']

[{'algorithm': 'auto', 'n_neighbors': 1},
 {'algorithm': 'auto', 'n_neighbors': 2},
 {'algorithm': 'auto', 'n_neighbors': 3},
 {'algorithm': 'auto', 'n_neighbors': 4},
 {'algorithm': 'auto', 'n_neighbors': 5},
 {'algorithm': 'auto', 'n_neighbors': 6},
 {'algorithm': 'auto', 'n_neighbors': 7},
 {'algorithm': 'auto', 'n_neighbors': 8},
 {'algorithm': 'ball_tree', 'n_neighbors': 1},
 {'algorithm': 'ball_tree', 'n_neighbors': 2},
 {'algorithm': 'ball_tree', 'n_neighbors': 3},
 {'algorithm': 'ball_tree', 'n_neighbors': 4},
 {'algorithm': 'ball_tree', 'n_neighbors': 5},
 {'algorithm': 'ball_tree', 'n_neighbors': 6},
 {'algorithm': 'ball_tree', 'n_neighbors': 7},
 {'algorithm': 'ball_tree', 'n_neighbors': 8},
 {'algorithm': 'kd_tree', 'n_neighbors': 1},
 {'algorithm': 'kd_tree', 'n_neighbors': 2},
 {'algorithm': 'kd_tree', 'n_neighbors': 3},
 {'algorithm': 'kd_tree', 'n_neighbors': 4},
 {'algorithm': 'kd_tree', 'n_neighbors': 5},
 {'algorithm': 'kd_tree', 'n_neighbors': 6},
 {'algorithm': 'kd

In [175]:
gs.best_params_

{'algorithm': 'auto', 'n_neighbors': 7}

In [176]:
gs.cv_results_['mean_test_score']

array([0.60690476, 0.63595238, 0.63142857, 0.63642857, 0.61666667,
       0.59690476, 0.66690476, 0.61666667, 0.60690476, 0.63595238,
       0.63142857, 0.63642857, 0.61666667, 0.59690476, 0.66690476,
       0.61666667, 0.60690476, 0.63595238, 0.63142857, 0.63642857,
       0.61666667, 0.59690476, 0.66690476, 0.61666667, 0.60690476,
       0.63595238, 0.63142857, 0.63642857, 0.61666667, 0.59690476,
       0.66690476, 0.61666667])

In [177]:
print(gs.score(X_test,y_test))

0.6565656565656566


In [178]:
from sklearn.model_selection import RandomizedSearchCV
knn_clf_rs = KNeighborsClassifier()
knn_clf_rs.fit(X_train,y_train)
param_rs = {'n_neighbors': list(range(1,9)),'algorithm':('auto','ball_tree','kd_tree','brute')}

In [179]:
sample = 8
randomCV = RandomizedSearchCV(knn_clf_rs,param_distributions=param_rs, n_iter=sample,cv=3)

In [180]:
X,Y

(array([[2.00000e+00, 1.00000e+00, 5.30101e+05, ..., 1.13000e+04,
         0.00000e+00, 0.00000e+00],
        [1.00000e+00, 1.00000e+00, 5.34817e+05, ..., 2.20800e+03,
         0.00000e+00, 0.00000e+00],
        [2.00000e+00, 1.00000e+00, 5.30334e+05, ..., 0.00000e+00,
         0.00000e+00, 0.00000e+00],
        ...,
        [1.00000e+00, 1.00000e+00, 5.29386e+05, ..., 3.20500e+03,
         0.00000e+00, 0.00000e+00],
        [1.00000e+00, 1.00000e+00, 5.30612e+05, ..., 2.20800e+03,
         0.00000e+00, 0.00000e+00],
        [1.00000e+00, 1.00000e+00, 5.34618e+05, ..., 6.11200e+03,
         0.00000e+00, 0.00000e+00]], dtype=float32),
 array([2., 2., 1., 1., 2., 2., 2., 2., 2., 1., 1., 2., 2., 1., 2., 2., 1.,
        2., 1., 2., 2., 2., 2., 2., 2., 2., 1., 1., 2., 2., 2., 1., 2., 1.,
        2., 2., 1., 2., 1., 2., 2., 1., 2., 2., 2., 2., 1., 2., 2., 1., 1.,
        1., 2., 1., 1., 1., 2., 2., 1., 2., 2., 2., 1., 2., 1., 2., 2., 1.,
        2., 1., 1., 1., 2., 1., 2., 2., 2., 2., 2., 1.

In [182]:
y=df[8]
X=df.drop([8],axis=1)

randomCV.fit(X,y)
print(randomCV.best_params_)

{'n_neighbors': 8, 'algorithm': 'ball_tree'}
